# Python Project Euler - Problem 2 - Deniz Jasarbasic

# Question: Each new term in the Fibonacci sequence is generated by 
# adding the previous two terms. By considering the terms in the Fibonacci 
# sequence whose values do not exceed four million, find the sum of the 
# even-valued terms.

# Solution:

# An iterative implementation of the Fibonacci sequence sum of even numbers.
def compute_sum():
    
    result = 0
    curr = 1
    next = 2
     
    while (curr <= 4000000):

        if (curr%2 == 0):
            result += curr
             
        curr, next = next, curr + next

    return result

print(compute_sum())